title: "Labora"
description: "Homelab Dashboard - Übersicht Dienste & Status"
theme: "system"
auth:
  enabled: false
groups:
  - name: "Core"
    icon: "Server"
    order: 0
  - name: "Netzwerk"
    icon: "Globe"
    order: 1
  - name: "Apps"
    icon: "Boxes"
    order: 2
services:
  - name: "Proxmox"
    url: "https://proxmox.lan:8006"
    icon: "Cpu"
    group: "Core"
    tags: ["vm", "infra"]
    vlan: 10
    health:
      type: "http"
      url: "https://proxmox.lan:8006/api2/json/version"
      interval: 30
    order: 0
  - name: "pfSense"
    url: "https://pfsense.lan"
    icon: "Shield"
    group: "Netzwerk"
    tags: ["router", "firewall"]
    vlan: 10
    health:
      type: "ping"
      host: "pfsense.lan"
      interval: 30
    order: 1
  - name: "AdGuard"
    url: "http://10.0.20.103"
    icon: "Filter"
    group: "Netzwerk"
    tags: ["dns", "adblock"]
    vlan: 20
    order: 2
  - name: "NPM"
    url: "http://10.0.20.102"
    icon: "Globe"
    group: "Netzwerk"
    tags: ["reverse-proxy", "ssl"]
    vlan: 20
    order: 3
  - name: "Portainer"
    url: "http://10.0.20.101:9000"
    icon: "Container"
    group: "Apps"
    tags: ["docker", "container"]
    vlan: 20
    order: 4
  - name: "Grafana"
    url: "http://10.0.20.100:3000"
    icon: "BarChart"
    group: "Apps"
    tags: ["monitoring", "metrics"]
    vlan: 20
    order: 5
discovery:
  enabled: true
  cidr: ["10.0.10.0/24", "10.0.20.0/24", "10.0.30.0/24", "10.0.40.0/24", "10.0.99.0/24"]
  http_ports: [80, 443, 3000, 8080, 9000]
  ping_timeout_ms: 600
widgets:
  proxmox:
    enabled: true
  pfsense:
    enabled: true
  adguard:
    enabled: true
  npm:
    enabled: true
